# Radius: Delrez et al., (2018) corrected by Kane et al., (2018)
# Masses: Grimm et al., (2018)
# Gravity: g*mass/(R2)
# Flux: Delrez et al., (2018) corrected by Kane et al., (2018)
# Density (Jontof-Hutter et al., 2014): radii: Delrez et al., (2018) + masses: Grimm e al (2018) corrected by Kane et al., (2018)
# Updated using the analysis done by Agol+2020 and references therein.

name = "TRAPPIST-1e-bm"
type = "layered"
radius = 5868000.0
radius_error_pos = 82000.0
radius_error_neg = 75000.0
mass = 2.316e+24
mass_error_pos = 1.3e+23
mass_error_neg = 1.3e+23
semi_major_axis = 4376000000.0
semi_major_axis_error_pos = 37000000.0
semi_major_axis_error_neg = 37000000.0
semi_major_axis_in_au = false
eccentricity = 0.00447
eccentricity_error_pos = 0.00014
eccentricity_error_neg = 0.00014
force_spin_sync = true

[tides]
model = "global_approx"
fixed_q = 100.0

[layers.Core]
type = "iron"
is_tidal = false
radius = 1760400.0
density = 12000.0

[layers.Mantle]
type = "rock"
is_tidal = true
radius = 5868000.0
density = 3300.0
